# Generated by Django 3.0 on 2020-06-13 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seobird657', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipebirdpage',
            old_name='coverImage',
            new_name='cover_image',
        ),
    ]
