# Generated by Django 3.0 on 2020-06-29 20:04

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('seobird657', '0005_auto_20200629_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipebirdpage',
            name='body',
            field=wagtail.fields.StreamField([('recipe', wagtail.blocks.StructBlock([('ingredients', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('ingredient', wagtail.blocks.CharBlock()), ('amount', wagtail.blocks.CharBlock(required=False))]))), ('instructions', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(required=False)), ('text', wagtail.blocks.CharBlock()), ('url', wagtail.blocks.URLBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))])))], null=True, required=False))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipebirdpage',
            name='recipe',
            field=wagtail.fields.StreamField([('ingredients', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('ingredient', wagtail.blocks.CharBlock()), ('amount', wagtail.blocks.CharBlock(required=False))]))), ('instructions', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(required=False)), ('text', wagtail.blocks.CharBlock()), ('url', wagtail.blocks.URLBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))])))], blank=True, null=True),
        ),
    ]
