# Generated by Django 3.1 on 2020-11-22 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seobird657', '0008_auto_20201025_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipebirdpage',
            name='recipe',
        ),
    ]
