# Generated by Django 3.1 on 2021-01-07 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('seobird657', '0011_auto_20201216_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssbirdpage',
            name='index_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
