# Generated by Django 3.1 on 2021-01-07 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seobird657', '0012_rssbirdpage_index_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rssbirdpage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='rssbirdpage',
            name='author_email',
        ),
    ]
