# Generated by Django 3.1.6 on 2021-05-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seobird657', '0013_auto_20210107_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='listbirdpage',
            name='transparent_header',
            field=models.BooleanField(default=False),
        ),
    ]
