# Generated by Django 3.2.11 on 2022-01-22 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seobird657', '0017_alter_recipebirdpage_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlebirdpage',
            old_name='show_coverImage',
            new_name='show_cover',
        ),
        migrations.RenameField(
            model_name='listbirdpage',
            old_name='show_coverImage',
            new_name='show_cover',
        ),
        migrations.RenameField(
            model_name='recipebirdpage',
            old_name='show_coverImage',
            new_name='show_cover',
        ),
    ]
