# Generated by Django 2.2 on 2020-04-25 14:07

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailimages', '0001_squashed_0021'),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeBirdPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('intro', wagtail.fields.RichTextField(blank=True, null=True)),
                ('show_breadcrumbs', models.BooleanField(default=False)),
                ('show_coverImage', models.BooleanField(default=False)),
                ('show_date', models.BooleanField(default=False)),
                ('exclude_from_sitemap', models.BooleanField(default=False)),
                ('recipe', wagtail.fields.StreamField([('ingredients', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('ingredient', wagtail.blocks.CharBlock()), ('amount', wagtail.blocks.CharBlock(required=False))]))), ('instructions', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(required=False)), ('text', wagtail.blocks.CharBlock()), ('url', wagtail.blocks.URLBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))])))])),
                ('coverImage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='RecipeBirdPageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='seobird657.RecipeBirdPage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seobird657_recipebirdpagetag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='recipebirdpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='seobird657.RecipeBirdPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
