# Generated by Django 3.1 on 2020-10-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seobird657', '0007_auto_20200918_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlebirdpage',
            old_name='cover_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='recipebirdpage',
            old_name='cover_image',
            new_name='image',
        ),
    ]
