# Generated by Django 4.1.7 on 2023-02-23 23:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("seobird657", "0019_alter_articlebirdpagetag_tag_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlebirdpage",
            name="author",
        ),
        migrations.RemoveField(
            model_name="listbirdpage",
            name="author",
        ),
        migrations.RemoveField(
            model_name="recipebirdpage",
            name="author",
        ),
    ]
